- libraries/Microsoft.Bot.Builder.Azure/Microsoft.Bot.Builder.Azure.csproj
- tests/Microsoft.Bot.Builder.Azure.Tests/AzureBlobTranscriptStoreTests.cs
Update `LongIdAddTest `from AzureStorageTranscriptStoreTests to work with Azure Storage Library v9.4.2
> Update LongIdAddTest to work with Azure Storage Library v9.4.2

- FunctionalTests/ExportedTemplate/template.json
- tests/Microsoft.Bot.Builder.TestBot/Controllers/BotController.cs
- tests/Microsoft.Bot.Builder.TestBot/Startup.cs
- Remove the _switch_-based bot assignation and its variable, and replace it with a `Func<string, IBot>` service.
- Add a different endpoint for each bot to the controller.
> [TestBot] Configure an endpoint for each bot

- Botkit/Microsoft.BotKit.Adapters.Slack/SlackAdapter.cs
Based on the work in PR #106, we fixed the assignation of the response id in _SendActivitiesAsync_ method.
``` CSharp
if (result.ok)
{
ResourceResponse response = new ResourceResponse() 
{
Id = (result as dynamic).ts
};
```
> Fix response.id assignation in SlackAdapter class

- Botkit/Microsoft.BotKit.Adapters.Slack/NewSlackMessage.cs
- Botkit/Microsoft.BotKit.Adapters.Slack/SlackAdapter.cs
- Change **ThreadTs** from DateTime to string in _NewSlackMessage_ class.
- Fix thread_ts assignation in _PostAsync_ method of _SlackAdapter_ class.
> Fix thread_ts assignation

- Botkit/Microsoft.BotKit.Adapters.Slack/SlackAdapter.cs
- Botkit/Microsoft.BotKit.Adapters.Slack/SlackMessage.cs
- Botkit/Microsoft.BotKit.Adapters.Slack/SlackResponse.cs
- Replaced _PostMessageAsync_ and _PostEphemeralMessageAsync_ methods of _Inumedia Slack_ library with _PostMessage_ and _PostEphemeral_ methods of _**Slack API**_ to fix the issue related to the bot not answering in threads.
- Add two auxiliary classes to handle Slack Response.
_The previous methods weren't considering the **thread_ts** field that was needed to reply a message in the corresponding thread._
> [Botkit] Refactor PostMessageAsync method

- libraries/Microsoft.BotKit.Adapters.Slack/ActivityResourceResponse.cs
- libraries/Microsoft.BotKit.Adapters.Slack/SlackAdapter.cs
Class `ActivityResourceResponse` was created, inheriting from `ResourceResponse` to receive the extra fields the code requires in the NodeJs version.
**The extra fields in this class are:**
1. ActivityID (string)
2. Conversation (ConversationAccount)
> Add class ActivityResourceResponse

- libraries/Microsoft.BotKit/Core/BotkitSlackMessage.cs
- libraries/Microsoft.BotKit/Core/IBotkitHandler.cs
Fix StyleCop warnings in _**BotkitSlackMessage**_ and **_IBotkitHandler_** classes.
- Add documentation for classes, methods, and properties.
- Remove unnecessary using statements.
> [Botkit] Fix warning in BotkitSlackMessage and IBotkitHandler classes

- libraries/Microsoft.BotKit.Adapters.Slack/AdapterError.cs
- libraries/Microsoft.BotKit/BotkitBotFrameworkAdapter.cs
Fix warnings on **AdapterError**.cs and **BotKitBotFrameworkAdapter**.cs files.
- Resolve privacy issue
- Add black line
- Constructor not follow a prop
- Order using directives alphabetically by namespace
- Constructor documentation 
- Constructor initializer line
- Add spaces into sentences
- Add return type to Documentation
- Add final period to Documentation
- Remove final space into starting/closing brace 
- Remove trailing whitespace 
- Change property’s name to upper case
> [StyleCop] Fix warnings on AdapterError and BotKitBotFrameworkAdapter

- libraries/Microsoft.BotKit.Adapters.Slack/DialogData.cs
- libraries/Microsoft.BotKit.Adapters.Slack/DialogElement.cs
- libraries/Microsoft.BotKit/BotWorker.cs
- libraries/Microsoft.BotKit/CMS/CMSConfiguration.cs
- Save files with encoding UTF-8 with BOM.
- Add value documentation to properties.
- Reorder constructor and properties.
> [StyleCop] Fix remaining warnings in BotWorker, DialogData, DialogElement and CMSConfiguration class

- libraries/Microsoft.BotKit.Adapters.Slack/SlackBotWorker.cs
Change the way the example is written in the doc comment to not to cause StyleCop parser to mark as failed.
> [StyleCop] SlackBotWorker - Remove conflicting characters in documentation comment

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioEvent.cs
- Replaced the `as dynamic` casting with casting to TwilioEvent class.
- Add two properties to TwilioEvent class needed in the adapter. The _EventType_ and _MediaUrl_ properties.
> [Botkit][Twilio] Remove 'as dynamic' casting

- tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.Tests/TwilioAdapterTests.cs
- Add test `Constructor_WithArguments_Succeeds ` to validate the creation of the TwilioAdapter when ITwilioAdapterOptions has its properties
> [TwilioAdapter] Create test for successful constructor of TwilioAdapter

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioHelper.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioMessage.cs
Added support for handling the message format when using Twilio's [Conversation API](https://www.twilio.com/docs/conversations)
When using the Conversation API the received payload differs from the format used for [standard SMS sending and receiving](https://www.twilio.com/docs/sms/api/message-resource#message-properties), with the structure of the message varying between the different events ([link](https://www.twilio.com/docs/conversations/conversations-webhooks)). 
Among other changes, the sender's phone number is stored in the **Author** field instead of **From**. This change adds support for both properties.
**Modified classes:**
* TwilioHelper.cs
* TwilioMessage.cs
> [TwilioAdapter] Add support for Twilio Conversations API

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/ITwilioClient.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioApi.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.Tests/TwilioAdapterTests.cs
This fixes ISSUE 2413
Change the parameter type in **GetResourceIdentifier** from object to **CreateMessageOptions**, since it's both created as that, and then immediately cast to that after being passed to the method.
Also, changed the name of the method to something better representing its function (**SendMessage**), since it creates and sends a message, and returns its resource identifier once sent.
**Modified classes:**
- ITwilioClient
- TwilioAdapter
- TwilioApi
Test methods updated accordingly and all of them passing.
> [TwilioAdapter] Change GetResourceIdentifier method signature

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/IWebexAdapterOptions.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/Microsoft.Bot.Builder.Adapters.Webex.csproj
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs
_**Note:** This PR is based on PR #178 and will be rebased once that one is merged._
I recommend reviewing this PR commit by commit, as it contains gradual changes that might not be obvious if the final changes are compared directly with the base code.
Most complex commit changes contain a body with a brief explanation.
The following changes were not done as they are more complex than the changes intended for this PR.
[DecryptedMessageToActivityAsync](https://github.com/southworkscom/botbuilder-dotnet/blob/856e85183bd8a935c589035fa8ae13f4c9236665/libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs) is still to big and does multiple things.
Ideally the following lines should be extracted to a private method. https://github.com/southworkscom/botbuilder-dotnet/blob/a39bc85 …
> [WebEx Adapter] Make several refactor improvements

- libraries/Microsoft.Bot.Builder.Dialogs/Choices/ChoiceRecognizers.cs
- libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj
- libraries/Microsoft.Bot.Builder.Dialogs/Prompts/NumberPrompt.cs
This PR upgrades the version of Recognizers-Text from [v1.1.3](https://github.com/microsoft/Recognizers-Text/releases/tag/dotnet-v1.1.3) to [v1.2.6](https://github.com/microsoft/Recognizers-Text/releases/tag/dotnet-v1.2.6) (latest stable version).
- Change versions of  `Microsoft.Recognizers.Text.Choice` and `Microsoft.Recognizers.Text.DateTime` on `Microsoft.Bot.Builder.Dialogs` to `v.1.2.6`
- Add `NumberOptions.SuppressExtendedTypes` to the NumberRecognizer in `ChoiceRecognizers`
> Upgrade Recognizers-Text version from v1.1.3 to v1.2.6

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexClientWrapper.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Files/MessageWithInputs.json
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Files/MessageWithText.json
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Files/PayloadAttachmentActions.json
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Files/WebhookAttachmentActions.json
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Files/WebhookList.json
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Microsoft.Bot.Builder.Adapters.Webex.Tests.csproj
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/WebexAdapterTests.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/WebexHelperTests.cs
Add unit tests to cover the new adaptive cards functionality.
- Added 3 tests for _AttachmentActionToActivity_ method
- Added 2 tests for _RegisterAdaptiveCardsWebhookSubscriptionAsync_ method
- Added 1 test for _ProcessAsync_ method 
- Added 1 tests for _SendActivitiesAsync_ method
- Simplified code by using var instead of specific types and simplifying default parameters
> [Webex] Add unit tests to cover adaptive cards functionality

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexHelper.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Files/Payload.json
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Files/Payload2.json
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Files/WebhookList.json
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/WebexAdapterTests.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/WebexHelperTests.cs
- Add an extra unit test to cover the regex evaluation in **DecryptedMessageToActivity**.
- Improve regex implementation in Helper class.
- Correct webhook name. 
**Modified Files**
- WebexAdapter.cs
- WebexHelper.cs
- Payload.json
- Payload2.json
- WebookList.json
- WebexHelperTests.cs
- WebexAdapterTests.cs
> [Webex Adapter] Add regex coverage test

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackHelper.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.TestBot/ConfigurationSlackAdapterOptions.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.TestBot/SimpleSlackAdapterOptions.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.TestBot/appsettings.json
- Add SlackHelper class to gather all auxiliary methods.
- Create SlackHelper class and move ActivityToSlack and VerifySignature methods in it.
- Remove ActivityToSlack and VerifySignature methods from SlackAdapter class
- Refactor VerifySignature method to adjust it to use the SigningSecret instead of the deprecated [VerificationToken](https://api.slack.com/docs/verifying-requests-from-slack)
- Adjust the setting of TestBot credentials to use the Signing Secret.
> [SlackAdapter] Add helper class

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/ActivityResourceResponse.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackDialog.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackMessage.cs
Apply naming conventions to keep consistency with the rest of the SDK.
- Private properties start with an underscore (e.g. _options).
- Use camelcase in names of properties and variables.
> [SlackAdapter] Apply naming conventions

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapterOptions.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexClientWrapper.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexHelper.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.TestBot/ConfigurationWebexAdapterOptions.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.TestBot/Controllers/BotController.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.TestBot/Startup.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/WebexAdapterTests.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/WebexHelperTests.cs
- Change property PublicAddress type from string to Uri
- Refactor RegisterWebhooksAsync method
- Move GetIdentityAsync call inside the adapter
- Make CancellationToken parameter mandatory
- Remove underscores from tests names
- Move methods related to the API to WebexClientWrapper class
- Move _config parámeter to WebexClientWrapper constructor
- Update Unit tests
> [WebexAdapter] Apply new feedback

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackHelper.cs
Remove _as dynamic_ castings for ChannelData by simply casting it to NewSlackMessage. Some conversions needed to be done to take into account Slack handling of timestamp.
A bigger refactor might come in handy in the future as well.
**Modified Files**
- SlackAdapter.cs
- SlackHelper.cs
> [Slack Adapter] Remove most dynamic castings

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapterOptions.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.TestBot/SimpleSlackAdapterOptions.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.TestBot/Startup.cs
As part of the feedback given for other adapters, we turned the ISlackAdapter interface into the SlackAdapter class. With the corresponding changes in the project.
**Modified files:**
- SlackAdapter.cs (renamed from ISlackAdapter.cs)
- DialogElement.cs
- SlackAdapterOptions.cs
- SimpleSlackAdapterOptions.cs
- Startup.cs
> [Slack Adapter] Turn ISlackAdapter interface into a class

- CodeCoverage.runsettings
Update the `CodeCoverage.runsettings` file for adding the Slack project to Code Coverage.
- [Customizing code coverage](https://docs.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2019)
> Add Slack Adapter project to CodeCoverage

- Microsoft.Bot.Builder.sln
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/Microsoft.Bot.Builder.Adapters.Slack.Tests.csproj
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/SlackAdapterTests.cs
- Create the `Microsoft.Bot.Builder.Adapters.Slack.Tests` project for testing the Slack Adapter
- Create the `SlackAdapterTests` file for testing the SlackAdapter class. Until now, it only tests the Constructor.
> [SlackAdapter] Add slack adapter unit tests

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/NewSlackMessage.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapterOptions.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackClientWrapper.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackHelper.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.TestBot/Startup.cs
Fixed warnings by Roslyn as well as applied the feedback added by Gabo in previous adapters, 
consisting of:
- Adding ConfigureAwait(false) to the async calls since this is a library.
- Passing on cancellation tokens inside async methods when available.
- Correctly using string.NotNullOrEmpty and similar when working with strings.
- Using status codes from HttpStatusCode enum.
**Modified files**
- SlackAdapter.cs
- SlackAdapterOptions.cs
- SlackClientWrapper.cs
- SlackHelper.cs
> [Slack Adapter] Fix Roslyn warnings and adapters feedback

- Microsoft.Bot.Builder.sln
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackClientWrapper.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackHelper.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/Microsoft.Bot.Builder.Adapters.Slack.Tests.csproj
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/SlackAdapterTests.cs
- Change Microsoft.Bot.Builder.Adapters.Slack.Tests project type from library to console app.
- Fix SlackAdapter constructor tests.
- Add Unit tests for UpdateActivityAsync method.
- Small refactor of UpdateActivityAsync method to return separate exceptions.
- Small refactor of TestAuthAsync to return only the user Id that is needed.
- Add null validations in ActivityToSlack method.
> [SlackAdapter] Add unit tests for UpdateActivityAsync

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackClientWrapper.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackHelper.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.TestBot/Startup.cs
Moved methods that don't belong to the Slack Adapter class into either the API Wrapper or the Helper class, leaving the Adapter to deal with only the BotAdapter responsibilities.
**Methods moved from SlackAdapter:**
- LoginWithSlack
- GetBotUserByTeamAsync
**Properties moved from SlackAdapter:**
- Options 
- Identity
**Methods deleted:**
- GetInstallLink (not used)
- ValidateOauthCodeAsync (not used)
- GetAPIAsync (deprecated)
> [Slack Adapter] Move methods from SlackAdapter class

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackClientWrapper.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackHelper.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/Files/MessageBody.json
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/Microsoft.Bot.Builder.Adapters.Slack.Tests.csproj
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/SlackAdapterTests.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/SlackClientWrapperTests.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/SlackHelperTests.cs
- Add unit tests for the following methods:
- DeleteActivityAsync
- UpdateActivityAsync
- VerifySignature
- ActivityToSlack
- GetMessageFromSlackEvent
> [Slack adapter] Add unit tests

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexClientWrapper.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexMessageRequest.cs
Add `ExcludeFromCodeCoverage` attribute to WebexClientWrapper and WebexMessageRequest classes to exclude them from Code Coverage.
> [WebexAdapter] Exclude from CC POCO and Wrapper classes

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackClientWrapper.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/SlackAdapterTests.cs
- Added unit tests for SendActivitiesAsync method
- Moved PostMessage code to SlackClientWrapper class.
- Added null parameter validations.
- Fixed parameter validations in UpdateActivityAsync and its tests.
> [SlackAdapter] Add unit tests for SendActivitiesAsync

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/SlackAdapterTests.cs
- Remove duplicated login from SlackAdapter constructor.
- Add mocking of TestAuthAsync method in tests.
- Remove TODO comment.
> [Slack adapter] Fix tests timeout

- Microsoft.Bot.Builder.sln
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/FacebookAdapterTests.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/Files/Payload.json
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/Microsoft.Bot.Builder.Adapters.Facebook.Tests.csproj
Added most of the tests for the adapter class.
**Added test**
- ConstructorShouldFailWithNullClient
- ConstructorWithArgumentsShouldSucceed
- ContinueConversationAsyncShouldFailWithNullConversationReference
- ContinueConversationAsyncShouldFailWithNullLogic
- ContinueConversationAsyncShouldSucceed
- DeleteActivityAsyncShouldThrowNotImplementedException
- ProcessAsyncShouldThrowExceptionWithInvalidBody
- ProcessAsyncShouldSucceed
- SendActivitiesAsyncShouldFailWithActivityTypeNotMessage
- SendActivitiesAsyncShouldSucceedWithActivityTypeMessage
- UpdateActivityAsyncShouldThrowNotImplementedException
**Added files**
- FacebookAdapterTests.cs
- Payload.json
- Microsoft.Bot.Builder.Adapters.Facebook.Tests.csproj
> [Facebook Adapter] Add most of adapters tests

- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/FacebookAdapterTests.cs
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/Files/PayloadWithStandby.json
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/Microsoft.Bot.Builder.Adapters.Facebook.Tests.csproj
Added more tests to reach a 97% of coverage in FacebookAdapter.
**Added tests**
- ProcessAsyncShouldSucceedWithStandbyMessages
- ProcessAsyncShouldReturnWhenHubModeSubscribe
- ProcessAsyncShouldThrowExceptionWithUnverifiedSignature
- SendActivitiesAsyncShouldSucceedWithActivityTypeMessageAndAttachments
> [Facebook Adapter] Add tests for standby messages and adapter

- CodeCoverage.runsettings
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/FacebookAdapterTests.cs
Some files are excluded from the CodeCoverage result and an Adapter test is fixed.
> [botkit] Facebook Handover - Exclude CodeCoverage Files

- tests/Microsoft.Bot.Builder.Dialogs.Declarative.Tests/SchemaMergeTests.cs
This change omits our dialog tests from the schema validation pool, making the pipeline succeed.
> We believe the schema validation comes up with a false negative. 
> Given that there is a precedent of omitting dialogs in the tet itself, we add our dialogs to it.
> [internal] Fixes southworks/add/BeginSkill-test

- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/Files/MessageBodyWithFileShare.json
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/Microsoft.Bot.Builder.Adapters.Slack.Tests.csproj
- tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/SlackHelperTests.cs
Internal PR for adding tests to the `southworks/update/slack-adapter-attachments` branch.
> Add test for Slack Adapter file sharing

- BotBuilder-DotNet.ruleset
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackClientWrapper.cs
- libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexClientWrapper.cs
- libraries/Microsoft.Bot.Builder.Azure.Blobs/BlobsTranscriptStore.cs
- libraries/Microsoft.Bot.Builder.Azure/AzureBlobStorage.cs
- libraries/Microsoft.Bot.Builder.Azure/AzureBlobTranscriptStore.cs
- libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Converters/JObjectConverter.cs
- libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/LanguageGeneratorManager.cs
- libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Generators/TemplateEngineLanguageGenerator.cs
- libraries/Microsoft.Bot.Builder.Dialogs.Debugging/Base/ActiveObject.cs
- libraries/Microsoft.Bot.Builder.Dialogs.Debugging/DialogDebugAdapter.cs
- libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Converters/InterfaceConverter.cs
- libraries/Microsoft.Bot.Builder.Dialogs.Declarative/Resources/ResourceExplorer.cs
- libraries/Microsoft.Bot.Builder/Adapters/TestFlow.cs
- libraries/Microsoft.Bot.Configuration/BotConfiguration.cs
- libraries/Microsoft.Bot.Connector/Authentication/AdalAuthenticator.cs
- libraries/Microsoft.Bot.Connector/ConversationsEx.cs
- libraries/Microsoft.Bot.Streaming/ProtocolAdapter.cs
- libraries/Microsoft.Bot.Streaming/ReceiveRequestExtensions.cs
- libraries/Microsoft.Bot.Streaming/ReceiveResponseExtensions.cs
- libraries/Microsoft.Bot.Streaming/Transport/WebSocket/WebSocketTransport.cs
#minor
This PR applies the feedback left on PR# 5068.
- Fixed issues related to rule VSTHRD103 by adding `await` and `ConfigureAwait(false)`.
- Ignored rules VSTHRD002, VSTHRD003, and VSTHRD011 in **_BotBuilder-DotNet.ruleset_**, and removed related _pragma_ sentences.
- Fix the VSTHRD105 issue by adding `TaskScheduler.Default`.
These images show the pipeline running and the test passing after the changes.
> Apply feedback on PR# 5068

- libraries/Microsoft.Bot.Connector/RetryAction.cs
- libraries/Microsoft.Bot.Connector/Teams/TeamsOperations.cs
- tests/Microsoft.Bot.Builder.Tests/Teams/TeamsInfoTests.cs
#minor
This PR adds retry logic to the _Send Message to List of Users_ Teams batch operation.
- Executes _SendMessageToListOfUsersWithRetryAsync_ in a Retry block.
- Throws a new ThrottleException if the API's return code is 429.
- Adds _HandleThrottlingException_ method to handle the new exception.
> Add retry logic to SendMessageToListOfUsersAsync

- libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs
- libraries/Microsoft.Bot.Connector/Teams/TeamsOperations.cs
- libraries/Microsoft.Bot.Connector/Teams/TeamsOperationsExtensions.cs
- tests/Microsoft.Bot.Builder.Tests/Teams/TeamsInfoTests.cs
#minor
This PR implements the SendMessageToAllUsersInTeam method of the new Teams batch APIs in TeamsOperations.
- Implemented the new methods of **_SendMessageToAllUsersInTeam_** in **_TeamsOperations_**, **_TeamsOperationsExtensions_**, and **_TeamsInfo_**.
> Implementation of SendMessageToAllUsersInTeam Teams batch APIs

- libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs
- libraries/Microsoft.Bot.Connector/Teams/TeamsOperations.cs
- libraries/Microsoft.Bot.Connector/Teams/TeamsOperationsExtensions.cs
- tests/Microsoft.Bot.Builder.Tests/Teams/TeamsInfoTests.cs
#minor
This PR implements the SendMessageToListOfChannels method of the new Teams batch APIs in TeamsOperations.
- Implemented the new methods of **_SendMessageToListOfChannels_** in **_TeamsOperations_**, **_TeamsOperationsExtensions_**, and **_TeamsInfo_**.
> Implementation of SendMessageToListOfChannels Teams batch APIs

- libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs
- libraries/Microsoft.Bot.Connector/Teams/TeamsOperations.cs
- libraries/Microsoft.Bot.Connector/Teams/TeamsOperationsExtensions.cs
- libraries/Microsoft.Bot.Schema/Teams/BatchOperationResponse.cs
- libraries/Microsoft.Bot.Schema/Teams/BatchOperationState.cs
- tests/Microsoft.Bot.Builder.Tests/Teams/TeamsInfoTests.cs
#minor
This PR implements the GetOperationState method of the new Teams batch APIs in TeamsOperations.
- Implemented the new methods of **_GetOperationStatet_** in **_TeamsOperations_**, **_TeamsOperationsExtensions_**, and **_TeamsInfo_**.
> Implementation of GetOperationState Teams batch APIs

- libraries/Microsoft.Bot.Builder/Teams/TeamsInfo.cs
- libraries/Microsoft.Bot.Connector/Teams/TeamsOperations.cs
- libraries/Microsoft.Bot.Connector/Teams/TeamsOperationsExtensions.cs
- libraries/Microsoft.Bot.Schema/Teams/BatchFailedEntriesResponse.cs
- libraries/Microsoft.Bot.Schema/Teams/BatchFailedEntry.cs
- tests/Microsoft.Bot.Builder.Tests/Teams/TeamsInfoTests.cs
#minor
This PR implements the Get failed entries paginated operation of the new Teams batch APIs in TeamsOperations.
**_NOTE: The API is not working yet, we forced the response for testing. Also, the specs for the use of the continuation token to call for consequent results are still pending._**
- Implemented the new methods of **_GetPagedFailedEntriesAsync_** in **_TeamsOperations_**, **_TeamsOperationsExtensions_**, and **_TeamsInfo_**.
- Added **_BatchFailedEntriesResponse_** and **_BatchFailedEntry_** classes to handle the API response object.
These images show the new unit tests passing and the new functionality tested with a sample bot.
> Implement GetPagedFailedEntriesAsync Teams Batch API
