ApiCompatTask/source/apiCompatCommand.ts, ApiCompatTask/source/commandLineResult.ts, ApiCompatTask/source/index.ts
- Add class to handle command line results
- Add class to handle ApiCompat commands
- Delegate responsabilities to those classes
- Clean up index.ts
=> [ApiCompat] Refactor of the task

ApiCompatTask/source/apiCompatCommand.ts, ApiCompatTask/source/commandLineResult.ts, ApiCompatTask/source/index.ts
- Fix calling of `optionalParameters` function
- Fix `compatibilityResult` result return when succeeded
- Validate `_totalIssues` using `=== 0` to avoid JS ambiguity
- Break ternary validation into multiple lines to ease the reading
- Rename `compattibilityResult()` to `compatibilityResult()`
=> [ApiCompat] Refactor ApiCompatCommand and commandLineResult code

ApiCompatTask/source/index.ts, ApiCompatTask/source/task.json
- Add option to generate output files with the comparison result as content
- Make the generation of said files optional
=> [ApiCompat] Add support for the creation of files with the comparison result

ApiCompatTask/source/apiCompatCommand.ts, ApiCompatTask/source/task.json
**Note:** This PR is based on PR #70, will rebase once that is merged.
- Add support to select a baseline file to skip known issues
=> [ApiCompat Task] Add support for baseline files

ApiCompatTask/source/apiCompatCommand.ts, ApiCompatTask/source/index.ts
- Validate that the directories or paths exist
- Throw an error when a directory or path does not exist
=> [ApiCompat Task] Validate the existence of paths

Botkit/Microsoft.BotKit.Adapters.Slack/DialogData.cs, Botkit/Microsoft.BotKit.Adapters.Slack/DialogElement.cs, Botkit/Microsoft.BotKit.Adapters.Slack/ISlackAdapterOptions.cs, Botkit/Microsoft.BotKit.Adapters.Slack/NewSlackMessage.cs
- Add documentation for properties and methods and classes.
- Reorder constructors and properties.
- Remove unnecessary using statements.
=> [StyleCop] Fix issues in SlackAdapter's auxiliar classes

Botkit/Microsoft.BotKit/Conversation/IBotkitConversationStep.cs
-Add documentation for classes and methods.
-Remove multiple blank lines.
Note: 'Using directive should appear within a namespace declaration' and ‘The file header XML is invalid’ rules were ignored.
=> [StyleCop] Review and fix warnings on IBotkitConversationStep.cs

libraries/Microsoft.Bot.Configuration/BotConfiguration.cs, libraries/Microsoft.Bot.Configuration/Services/AppInsightsService.cs, libraries/Microsoft.Bot.Configuration/Services/AzureService.cs, libraries/Microsoft.Bot.Configuration/Services/BlobStorageService.cs, libraries/Microsoft.Bot.Configuration/Services/BotService.cs, libraries/Microsoft.Bot.Configuration/Services/ConnectedService.cs, libraries/Microsoft.Bot.Configuration/Services/CosmosDbService.cs, libraries/Microsoft.Bot.Configuration/Services/DispatchService.cs, libraries/Microsoft.Bot.Configuration/Services/EndpointService.cs, libraries/Microsoft.Bot.Configuration/Services/FileService.cs, libraries/Microsoft.Bot.Configuration/Services/GenericService.cs, libraries/Microsoft.Bot.Configuration/Services/LuisService.cs, libraries/Microsoft.Bot.Configuration/Services/QnAMakerService.cs, libraries/Microsoft.Bot.Connector/Authentication/AuthenticationConfiguration.cs, libraries/Microsoft.Bot.Connector/Authentication/JwtTokenExtractor.cs, libraries/integration/Microsoft.Bot.Builder.Integration.ApplicationInsights.Core/TelemetrySaveBodyASPMiddleware.cs, tests/Microsoft.Bot.Builder.TestBot/Dialogs/MainDialog.cs, tests/Microsoft.Bot.Builder.TestBot/Startup.cs, tests/Microsoft.Bot.Configuration.Tests/ConnectionTests.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/JwtTokenExtractorTests.cs, tests/Microsoft.Bot.Connector.Tests/Authentication/TestConfigurationRetriever.cs
- Add/remove spacing
- Separate _TestConfigurationRetriever_ class to its own file
- Fix field accessors
- Fix upper/lowercase letters
- Remove unnecessary using statements
- Change file encoding from _UTF-8_ to _UTF-8 with BOM_
=> [StyleCop] Fix all the warnings on Bot.Connector.Authentication.Tests

libraries/Microsoft.BotKit.Adapters.Slack/SlackEventMiddleware.cs, libraries/Microsoft.BotKit.Adapters.Slack/SlackMessageTypeMiddleware.cs
**Changes**
- Added documentation.
- Removed unnecesary usings.
=> [StyleCop] Fix warnings in SlackEventMiddleware.cs and SlackMessageTypeMiddleware.cs

libraries/Microsoft.BotKit.Adapters.Slack/SlackBotWorker.cs, libraries/Microsoft.BotKit/BotWorker.cs
- Revert change of **_config_** field from public to private in _BotWorker_ class.
- Convert field to property.
=> [Botkit] Fix breaking change introduce in BotWorker class.

libraries/Microsoft.BotKit/Channel.cs
Fix warnings on Channel.cs
**Changes**
- Add class documentation.
- Remove blank lines.
- Add documentation for methods properties.
=> [StyleCop] fix warnings on Channel

libraries/Microsoft.BotKit.Adapters.Slack/SlackAdapter.cs
Warnings from StyleCop were resolved in SlackAdapter.cs
=> Fix StyleCop warnings in Slack Adapter

libraries/Microsoft.BotKit.Adapters.Slack/SlackMessage.cs, libraries/Microsoft.BotKit.Adapters.Slack/SlackResponse.cs
**Changes**
- Add documentation.
- Refactor: change fields to properties.
=> [StyleCop] Fix warnings in SlackMessage.cs and SlackResponse.cs

Botkit/Microsoft.BotKit/Conversation/Collect.cs, Botkit/Microsoft.BotKit/Conversation/Execute.cs, libraries/Microsoft.BotKit/Conversation/IBotkitMessageTemplate.cs
- Remove blank lines
- Order using directives alphabetically by namespace
- Add final period to Documentation text
Note: ‘Using directive should appear within a namespace declaration’, 'File may only contain a single type' and ‘The file header XML is invalid’ rule was ignored.
=> [StyleCop] Fix issues in IBotkitMessageTemplate.cs

Botkit/Microsoft.BotKit/Core/IStoreItems.cs, Botkit/Microsoft.BotKit/Core/IWebserver.cs, libraries/Microsoft.BotKit/Core/Botkit.cs, libraries/Microsoft.BotKit/Core/BotkitConfiguration.cs
- Reordered using statements
- Reordered constructors and properties
- Add documentation for properties and methods
- Change public field Version to property
- Move interfaces to their own files
=> [StyleCop] Fix warnings in Botkit and BotkitConfiguration classes

libraries/Microsoft.BotKit/Core/IBotkitMessage.cs, libraries/Microsoft.BotKit/Core/IBotkitPlugin.cs, libraries/Microsoft.BotKit/Core/IBotkitTrigger.cs
Fix warnings on IBotkitMessage.cs, IBotkitPlugin.cs and IBotkitTrigger.cs files.
**### Changes made**
- Add separated blank line between elements
- Remove black line in signle-line comment
=> [StyleCop] Fix warnings on IBotkitMessage, IBotkitPluginand and IBotkitTrigger

libraries/BotKit Samples/Microsoft.Bot.Sample.Slack/ConfigurationCredentialProvider.cs, libraries/BotKit Samples/Microsoft.Bot.Sample.Slack/ConfigurationSlackAdapterOptions.cs, libraries/BotKit Samples/Microsoft.Bot.Sample.Slack/SimpleSlackAdapterOptions.cs
- Reordered using statements
- Save files with UTF-8 with BOM encoding
=> [StyleCop] Fix warnings in Bot.Sample.Slack project

libraries/Microsoft.BotKit.Adapters.Slack/SlackBotWorker.cs, libraries/Microsoft.BotKit.Adapters.Slack/SlackDialog.cs
**Changes**
- Added documentation.
- Removed and sorted unnecesary usings.
- Reorder blocks of code to avoid extra warnings.
=> [StyleCop] Fix warnings in SlackBotWorker.cs and SlackDialog.cs

libraries/BotKit Samples/Microsoft.Bot.Sample.Slack/SimpleSlackAdapterOptions.cs, libraries/Microsoft.BotKit.Adapters.Slack/ISlackAdapterOptions.cs
- Add value documentation for properties.
- Change parameter name to lowerCase.
=> [StyleCop] Fix warnings in ISlackAdapterOptions and SimpleSlackAdapterOptions files

libraries/Microsoft.BotKit.Adapters.Slack/SlackBotWorker.cs, libraries/Microsoft.BotKit.Adapters.Slack/SlackDialog.cs
Fix warnings on **SlackBotWorker**.cs and **SlackDialog**.cs files.
- Remove unused field
- Change embedded comment into ‘if’ block statement
=> [StyleCop] Fix warnings on SlackBotWorker and SlackDialog

libraries/Microsoft.BotKit.Adapters.Slack/SlackMessageTypeMiddleware.cs
Structure of Regex lines modified to comply with StyleCop
=> [StyleCop]Fix warnings in SlackMessageTypeMiddleware

libraries/Microsoft.BotKit/BotkitDialogWrapper.cs, libraries/Microsoft.BotKit/CMS/BotkitCMSHelper.cs, libraries/Microsoft.BotKit/Conversation/BotkitConversation.cs, libraries/Microsoft.BotKit/Core/Botkit.cs
- Add **CS1998 warning** disable statements
- Add throw _NotImplementedException_ in not implemented method
=> [Botkit] Ignore CS1998 warning in not implemented methods.

libraries/BotKit Samples/Microsoft.Bot.Sample.Slack/README.md
Update the Readme.md file for the Slack Adapter Sample explaining how to test it.
=> [Botkit] Update README for SlackAdapter sample

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/ITwilioAdapterOptions.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioEvent.cs
- Apply naming convention
- Replace explicit type with `var`
- Remove unnecessary `this`
- Remove unnecessary `.ToString()`
- Use object initializer
- Remove explicit type
- Replace `NotImplementedException` with `ApiException`
=> [Botkit][Twilio] Apply naming convection and other improvements

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs
- Replaced `Equals(string.Empty)` with `string.IsNullOrWhiteSpace` for checking string conditions.
- Replaced `for` loop with `foreach` loop as _ReSharper_ tool suggested.
- Added `cancellationToken` in _WriteAsync_ method as _ReSharper_ tool suggested.
=> [Botkit][Twilio] Improve null string conditions

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/ITwilioAdapterOptions.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioEvent.cs
Remove dynamic casting and improve documentation
=> [Botkit][Twilio] Remove dynamic casting and improve documentation

Microsoft.Bot.Builder.sln, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs, tests/Test Applications/Microsoft.Bot.Builder.Twilio.Sample/Bots/EchoBot.cs, tests/Test Applications/Microsoft.Bot.Builder.Twilio.Sample/ConfigurationCredentialProvider.cs, tests/Test Applications/Microsoft.Bot.Builder.Twilio.Sample/ConfigurationTwilioAdapterOptions.cs, tests/Test Applications/Microsoft.Bot.Builder.Twilio.Sample/Controllers/BotController.cs, tests/Test Applications/Microsoft.Bot.Builder.Twilio.Sample/DeploymentTemplates/template-with-new-rg.json, tests/Test Applications/Microsoft.Bot.Builder.Twilio.Sample/DeploymentTemplates/template-with-preexisting-rg.json, tests/Test Applications/Microsoft.Bot.Builder.Twilio.Sample/Microsoft.Bot.Builder.Twilio.Sample.csproj, tests/Test Applications/Microsoft.Bot.Builder.Twilio.Sample/Program.cs, tests/Test Applications/Microsoft.Bot.Builder.Twilio.Sample/SimpleTwilioAdapterOptions.cs, tests/Test Applications/Microsoft.Bot.Builder.Twilio.Sample/Startup.cs, tests/Test Applications/Microsoft.Bot.Builder.Twilio.Sample/appsettings.Development.json, tests/Test Applications/Microsoft.Bot.Builder.Twilio.Sample/appsettings.json, tests/Test Applications/Microsoft.Bot.Builder.Twilio.Sample/wwwroot/default.htm
- Refactored _ProcessAsync_ method to fix `Http response has already started` bug.
=> [Botkit][TwilioAdapter] Fix http response bug

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioEvent.cs
Refactor of code to grab attachments from message and hand them over to _activity.Attachments_
=> [Botkit] [Twilio] Add functionality for getting attachments

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioEvent.cs
- Add arguments validation
- Extract `HttpRequest` processing to a method
=> [TwilioAdapter] Refactor ProcessAsync

tests/Test Applications/Microsoft.Bot.Builder.Twilio.Sample/README.md
Added README.md file with instructions to connect a bot to Twilio and run the sample bot.
=> [Botkit][Twilio] Add README.md file to Twilio sample

tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.Tests/TwilioHelperTests.cs
`authTokenString`, `validationUrlString` made global variables in **TwilioHelperTests**
=> [TwilioAdapter] Make variables global in TwilioHelperTests

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs
- Rename `config` to `_config`
- Rename `api` to `_api`
- Remove unnecessary `this` due to renaming
=> [WebEx Adapter] Apply naming convention

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/IWebexAdapterOptions.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs
Improve some documentation that was carried over from the TypeScript project.
_**Note:** This PR is based on PR #176 and will be rebased once that one is merged._
=> [WebEx Adapter] Small fixes and improvements in code documentation

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs
Remove all -if possible- instances of casting variables to _dynamic_ type. This was generally due to Node JS weakly typed variables being ported to C#.
In this adapter, mostly all dynamic casts of ChannelData were typed as WebhookEventData. Other references were typed as Message class. Both from the Webex .NET library the project uses (https://github.com/thrzn41/WebexTeamsAPIClient).
=> [Webex Adapter] Remove dynamic casts

libraries/Microsoft.Bot.Builder.Dialogs/Microsoft.Bot.Builder.Dialogs.csproj, libraries/Microsoft.Bot.Builder/Microsoft.Bot.Builder.csproj
This PR adds a temporal description to the `.csproj` of `Microsoft.Bot.Builder` and `Microsoft.Bot.Builder.Dialogs` that includes the changes that come with the Recognizers-Text version upgrade.
- Add description to `Microsoft.Bot.Builder.csproj`
- Add description to `Microsoft.Bot.Builder.Dialogs`
This is what the preview looks like when the package is generated:
_Note: This is a temporal solution, in the future the release note should be changed. If the NuGet team adds the option to [add markdown](https://github.com/NuGet/Home/wiki/Packaging-Documentation-within-the-nupkg), we would probably want to link the changes instead of writing them down. However, this will do for an initial version upgrade._
=> [Documentation] Add changes on recognizers-text utterances to the package description

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/IWebexClient.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexApi.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexHelper.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.TestBot/Bots/EchoBot.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Files/Message.json, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Files/MessageAttachments.json, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Files/Payload.json, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Microsoft.Bot.Builder.Adapters.Webex.Tests.csproj, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/WebexAdapterTests.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/WebexHelperTests.cs
- Add support for message's attachments.
- Include unit tests for the new functionality
=> [Webex Adapter] Add message's attachments support

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexClientWrapper.cs
Main methods from **TeamsAPIClient** class from the [WebexAPIClient .NET library](https://github.com/thrzn41/WebexTeamsAPIClient) have been exposed through our wrapper class (**WebexClientWrapper**). 
Only the most comprehensive overloads have been exposed.
=> [WebexAdapter] Add API methods to API wrapper

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackClientWrapper.cs
Added an API wrapper class (**SlackClientWrapper**) to serve as a wrapper to Inumedia's [API library](https://github.com/Inumedia/SlackAPI). 
**Modified files**
- SlackAdapter
- SlackClientWrapper (created)
=> [SlackAdapter] Add API wrapper class

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexHelper.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.TestBot/Bots/EchoBot.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/WebexHelperTests.cs
Fix Regexes for striping mentions when messages have HTML content.
=> [WebexAdapter] Fix Regexes for messages with html content

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Webex/WebexHelper.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Files/MessageHtmlDecodedMention.json, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Files/MessageHtmlEncodedMention.json, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/Microsoft.Bot.Builder.Adapters.Webex.Tests.csproj, tests/Adapters/Microsoft.Bot.Builder.Adapters.Webex.Tests/WebexHelperTests.cs
- Add decoding of Identity.Id for matching mentions in message html.
- Fix regex adding `<div>` identifier to match mentions from Web Client
- Fix unit tests
=> [WebexAdapter] Add Id decoding to strip mention in messages html

tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/SlackAdapterTests.cs
- Add unit tests for ContinueConversationAsync method
- Add null parameter validation
=> [SlackAdapter] Add unit tests for ContinueConversationAsync

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/Microsoft.Bot.Builder.Adapters.Slack.csproj, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/NewSlackMessage.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackClientWrapper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackEvent.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Slack/SlackHelper.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.TestBot/Bots/EchoBot.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Slack.Tests/SlackHelperTests.cs
Add code for the Slack attachments to be processed by the adapter and taken into account in the message payload.
Also added code for the sample bot included to react to messages with attachments.
**Modified files**
- NewSlackMessage
- SlackAdapter
- SlackClientWrapper
- SlackEvent
- SlackHelper
- EchoBot
- SlackHelperTests
=> [Slack Adapter] Add attachments processing

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAPI.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapterOptions.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookMessage.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Message.cs
Did corrections according to previous work in past adapters to what was already done in Facebook Adapter.
- Remove unreferenced methods 
- Change type initializations to var 
- Add IDisposable handling 
- Remove this keyword
- Fix some Roslyn warnings
=> [Facebook Adapter] Initial corrections

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapterOptions.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookHelper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookMessage.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Message.cs
Added FacebookHelper class to house all methods that are not related to the adapter neither to the API wrapper. 
**Methods moved to the helper:**
- ActivityToFacebook
- ProcessSingleMessage (formerly async)
=> [Slack Adapter] Add Helper class

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs
Moved method implementations to the FacebookClientWrapper class and usings cleanup.
=> [Facebook Adapter] Migrate methods to FacebookClientWrapper

Microsoft.Bot.Builder.sln, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.TestBot/Bots/EchoBot.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.TestBot/Controllers/BotController.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.TestBot/DeploymentTemplates/template-with-new-rg.json, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.TestBot/DeploymentTemplates/template-with-preexisting-rg.json, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.TestBot/Microsoft.Bot.Builder.Adapters.Facebook.TestBot.csproj, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.TestBot/Program.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.TestBot/README.md, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.TestBot/Resources/adaptive_card.json, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.TestBot/Startup.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.TestBot/appsettings.Development.json, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.TestBot/appsettings.json, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.TestBot/wwwroot/default.htm
The `TestBot` for Facebook is added to be used it on .NET
- The `TestBot` Project was added and updated to the new version
=> [Botbuilder] Facebook TestBot in .Net

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookHelper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Message.cs
- Apply some small refactors proposed by ReSharper.
- Move WriteAsync to FacebookHelper to make testing easier.
- Make the VerifySignature method synchronic.
- Rename CallAPIAsync method for readability.
=> [Facebook Adapter] Small refactors

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.TestBot/Controllers/BotController.cs
- Add webhook validation 
- Fix message's signature validation
=> [Facebook Adapter] Add webhook validation

recognizers-text/Utterance Changes/Differences.md
New documentation to the Readme file was added.
=> [Botbuilder-DotNet] Add description to Readme

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.Tests/FacebookWrapperTests.cs
- Added the remaining **FacebookClientWrapper** tests.
- Fixed a hash in a failing test.
=> [Facebook Adapter] Add remaining wrapper tests

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Twilio/TwilioHelper.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Twilio.Tests/TwilioHelperTests.cs
=> [botkit] Apply Gary's feedback on twilio

Microsoft.Bot.Builder.sln, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookHelper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookMessage.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot/Bots/EchoBot.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot/Controllers/BotController.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot/DeploymentTemplates/template-with-new-rg.json, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot/DeploymentTemplates/template-with-preexisting-rg.json, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot.csproj, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot/Program.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot/README.md, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot/Resources/ButtonTemplatePayload.json, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot/Resources/GenericTemplatePayload.json, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot/Resources/HandoverTemplatePayload.json, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot/Resources/MediaTemplatePayload.json, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot/Startup.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot/wwwroot/default.htm, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.TestBot/Bots/EchoBot.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.TestBot/Resources/HandoverBotsTemplatePayload.json
Facebook Handover with a secondary bot and a live agent.
- Add Secondary Bot.
- Update Echo bot to using Handover functionalities
- Update Adapter and Helper classes
=> [botkit] Facebook Handover Functionality

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookClientWrapper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/AttachmentPayload.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookBotUser.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookQuickReply.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookResponseEvent.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/FacebookResponseOk.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Handover/FacebookPassThreadControl.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Handover/FacebookRequestThreadControl.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Handover/FacebookTakeThreadControl.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Handover/FacebookThreadControl.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Templates/Element.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookHelper.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookMessage.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/Message.cs
Do the corrections suggested by Roslyn and other code analyzers to the Facebook Handover Protocol changes.
=> [Facebook Adapter] Roslyn and formatting corrections

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookAdapter.cs, libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/FacebookEvents/Handover/HandoverConstants.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.PrimaryTestBot/Bots/PrimaryBot.cs
Added missing documentation to properties in FacebookConstants class
Also deleted unnecesary empty spaces in PrimaryBot
=> [Facebook Adapter] Add FacebookConstants documentation

libraries/Adapters/Microsoft.Bot.Builder.Adapters.Facebook/README.md
Add mention of support for Handover Protocol in readme file
=> [Facebook Adapter] Add comment in readme.md

tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.PrimaryTestBot/Bots/PrimaryBot.cs, tests/Adapters/Microsoft.Bot.Builder.Adapters.Facebook.SecondaryTestBot/Bots/SecondaryBot.cs
Moved the values for the app Ids to a constant on top for easiness of deployment.
=> [Facebook Adapter] Move app ids to constant value

FunctionalTests/Microsoft.Bot.Builder.FunctionalTests/FacebookChatTests.cs, build/yaml/botbuilder-dotnet-ci-facebook-test.yml
Adds a YAML file to set up a pipeline to run the functional test for Facebook
This pull request depends on the test added in the PR# 3250
We added the file `botbuilder-dotnet-ci-facebook-test.yml` inside the folder `build/yaml`.
The next steps will guide you through the configuration of a build pipeline based on this YAML file.
- Azure DevOps organization.
- Azure subscription. Required to create and delete Azure resources.
- App registration in Azure portal. [More info](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app).
- Configure an Azure Connection Service. [Steps here](#add-a-connection-service).
- Create a Facebook application and get the Facebook variables. [Steps here](#create-a-facebook-application-and-get-facebook-variables).
1- Create a …
=> Add build YAML for Facebook functional test

build/yaml/ci-test-steps.yml, libraries/Microsoft.Bot.Builder.AI.LUIS/LuisExtensions.cs, libraries/Microsoft.Bot.Builder/ActivityHandler.cs
=> Testing API Compat with changes in libraries

build/yaml/ci-test-steps.yml
=> Testing API Compat with no changes in libraries

libraries/Microsoft.Bot.Builder.Dialogs/Dialog.cs
=> Testing PR
